CREATE TABLE vialis.viajes
(
    id_tarjeta                 BIGINT,
    id_viaje                   SMALLINT,
    cantidad_etapas            SMALLINT,
    rango_horario              SMALLINT,

    etapas_subte               SMALLINT,
    etapas_tren                SMALLINT,
    etapas_colectivo           SMALLINT,

    geom_origen                GEOMETRY(Point, 4326),

    geom_destino               GEOMETRY(Point, 4326),

    h3_origen                  H3INDEX,
    h3_destino                 H3INDEX,

    departamento_origen_viaje  CHAR(5),
    departamento_destino_viaje CHAR(5),

    factor_expansion_viaje     REAL,

    etapas_incompletas         CHAR(1),
    genero                     CHAR(1),
    grupo_edad                 SMALLINT
);

-- Hexagono H3 --
CREATE TABLE vialis.hexagonos_viajes (
    indice_h3 H3INDEX PRIMARY KEY,
    punto_maxima_concurrencia GEOMETRY(Point, 4326),
    concurrencia DOUBLE PRECISION NOT NULL
);

-- Matriz origen-destino --
CREATE TABLE vialis.matriz_origen_destino (
    h3_origen H3INDEX NOT NULL
        REFERENCES vialis.hexagonos_viajes(indice_h3),
    h3_destino H3INDEX NOT NULL
        REFERENCES vialis.hexagonos_viajes(indice_h3),
    cantidad_viajes DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (h3_origen, h3_destino)
);

-- Cuadros tarifarios de colectivos por jurisdicción y distancia. Los importes
-- se guardan en centavos de ARS; distancia_max_metros NULL representa +infinito.
CREATE TABLE vialis.tarifas_colectivo (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jurisdiccion                    TEXT NOT NULL
        CHECK (jurisdiccion IN ('caba', 'province', 'national')),
    distancia_min_metros            INTEGER NOT NULL CHECK (distancia_min_metros >= 0),
    distancia_max_metros            INTEGER,
    tarifa_registrada_centavos      INTEGER NOT NULL CHECK (tarifa_registrada_centavos >= 0),
    tarifa_sin_registrar_centavos   INTEGER NOT NULL CHECK (tarifa_sin_registrar_centavos >= 0),
    CONSTRAINT tarifas_colectivo_distancia_valida CHECK (
        distancia_max_metros IS NULL
        OR distancia_max_metros > distancia_min_metros
    ),
    UNIQUE (jurisdiccion, distancia_min_metros)
);

-- Recorridos de colectivos GTFS --
CREATE TABLE vialis.recorridos (
    id_recorrido                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gtfs_route_id               TEXT NOT NULL,
    gtfs_shape_id               TEXT NOT NULL,
    nombre_publico              TEXT NOT NULL,
    linea                       TEXT NOT NULL,
    ramal                       TEXT NOT NULL,
    direction_id                SMALLINT NOT NULL CHECK (direction_id IN (0, 1)),
    destino                     TEXT,
    descripcion                 TEXT,
    geom                        GEOMETRY(LineString, 4326) NOT NULL,
    distancia_metros            INTEGER NOT NULL CHECK (distancia_metros >= 0),
    tiempo_total_minutos        SMALLINT CHECK (tiempo_total_minutos >= 0),
    caudal_pasajeros            INTEGER CHECK (caudal_pasajeros >= 0),
    ingreso_economico           BIGINT CHECK (ingreso_economico >= 0),
    UNIQUE (gtfs_route_id, direction_id)
);

CREATE INDEX idx_recorridos_geom
ON vialis.recorridos
USING GIST (geom);

-- El índice anterior es sobre la columna geom pelada, así que un ST_DWithin en
-- geography no puede usarlo y degrada a recorrer la tabla entera. La búsqueda
-- de corredores detrás de POST /lines/similar filtra en metros y no en grados,
-- por lo que necesita el índice sobre la expresión casteada. Es la misma
-- respuesta que ya da idx_recorridos_paradas_tramo_geography por la misma
-- razón. Se conservan los dos: el geométrico sigue sirviendo al filtro por caja
-- del listado, que compara cajas en grados.
CREATE INDEX idx_recorridos_geom_geography
ON vialis.recorridos
USING GIST ((geom::geography));

-- Una parada es una ubicación física y puede pertenecer a varios recorridos.
CREATE TABLE vialis.paradas (
    id_parada                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gtfs_stop_id                TEXT NOT NULL UNIQUE,
    codigo                      TEXT,
    nombre                      TEXT NOT NULL,
    posicion                    GEOMETRY(Point, 4326) NOT NULL
);

CREATE INDEX idx_paradas_posicion
ON vialis.paradas
USING GIST (posicion);

-- El indice anterior es sobre la columna pelada, en grados. La busqueda de
-- trasbordos entre recorridos mide caminatas en metros con ST_DWithin sobre
-- geography, que no puede usarlo y degradaria a recorrer las 43.594 paradas por
-- cada una. Es la misma razon por la que existe idx_recorridos_geom_geography.
CREATE INDEX idx_paradas_posicion_geography
ON vialis.paradas
USING GIST ((posicion::geography));

-- Relación ordenada entre un recorrido y sus paradas. El tramo y la distancia
-- son NULL para la última parada, porque no existe una parada siguiente.
CREATE TABLE vialis.recorridos_paradas (
    id_recorrido                       BIGINT NOT NULL
        REFERENCES vialis.recorridos(id_recorrido) ON DELETE CASCADE,
    id_parada                          BIGINT NOT NULL
        REFERENCES vialis.paradas(id_parada),
    nro_parada                         INTEGER NOT NULL CHECK (nro_parada >= 0),
    tramo_hasta_siguiente              GEOMETRY(LineString, 4326),
    distancia_hasta_siguiente_metros   INTEGER
        CHECK (distancia_hasta_siguiente_metros >= 0),
    tiempo_valle_hasta_siguiente_segundos INTEGER
        CONSTRAINT recorridos_paradas_tiempo_valle_positivo
        CHECK (tiempo_valle_hasta_siguiente_segundos > 0),
    tiempo_tipico_hasta_siguiente_segundos INTEGER
        CONSTRAINT recorridos_paradas_tiempo_tipico_positivo
        CHECK (tiempo_tipico_hasta_siguiente_segundos > 0),
    tiempo_pico_hasta_siguiente_segundos INTEGER
        CONSTRAINT recorridos_paradas_tiempo_pico_positivo
        CHECK (tiempo_pico_hasta_siguiente_segundos > 0),
    cantidad_muestras_tiempo           INTEGER NOT NULL DEFAULT 0
        CHECK (cantidad_muestras_tiempo >= 0),
    CONSTRAINT recorridos_paradas_muestras_tiempo_validas CHECK (
        (
            tiempo_valle_hasta_siguiente_segundos IS NULL
            AND tiempo_tipico_hasta_siguiente_segundos IS NULL
            AND tiempo_pico_hasta_siguiente_segundos IS NULL
            AND cantidad_muestras_tiempo = 0
        )
        OR (
            tiempo_valle_hasta_siguiente_segundos IS NOT NULL
            AND tiempo_tipico_hasta_siguiente_segundos IS NOT NULL
            AND tiempo_pico_hasta_siguiente_segundos IS NOT NULL
            AND tiempo_valle_hasta_siguiente_segundos
                <= tiempo_tipico_hasta_siguiente_segundos
            AND tiempo_tipico_hasta_siguiente_segundos
                <= tiempo_pico_hasta_siguiente_segundos
            AND cantidad_muestras_tiempo > 0
        )
    ),
    PRIMARY KEY (id_recorrido, nro_parada)
);

CREATE INDEX idx_recorridos_paradas_id_parada
ON vialis.recorridos_paradas (id_parada);

CREATE INDEX idx_recorridos_paradas_tramo_geography
ON vialis.recorridos_paradas
USING GIST ((tramo_hasta_siguiente::geography))
WHERE tramo_hasta_siguiente IS NOT NULL;

-- Versiones de la red vial importada desde OpenStreetMap. El pipeline conserva
-- el historial de cargas, pero sólo una puede describir las tablas activas.
CREATE TABLE vialis.calles_metadata (
    id_carga                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fuente_url                 TEXT NOT NULL,
    fecha_descarga             TIMESTAMPTZ NOT NULL,
    fecha_datos                TIMESTAMPTZ,
    checksum_sha256            CHAR(64) NOT NULL
        CHECK (checksum_sha256 ~ '^[0-9a-fA-F]{64}$'),
    alcance                    GEOMETRY(MultiPolygon, 4326) NOT NULL,
    herramienta_importacion    TEXT NOT NULL,
    version_herramienta        TEXT NOT NULL,
    cantidad_aristas           BIGINT CHECK (cantidad_aristas >= 0),
    cantidad_vertices          BIGINT CHECK (cantidad_vertices >= 0),
    proporcion_descartada      DOUBLE PRECISION
        CHECK (proporcion_descartada BETWEEN 0 AND 1),
    activa                     BOOLEAN NOT NULL DEFAULT FALSE,
    creada_en                  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX idx_calles_metadata_carga_activa
ON vialis.calles_metadata (activa)
WHERE activa;

-- Vértices de la red vial activa. osm_node_id queda nulo cuando el importador
-- necesita materializar un vértice que no corresponde a un nodo OSM original.
CREATE TABLE vialis.calles_vertices (
    id_vertice                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    osm_node_id                BIGINT UNIQUE,
    geom                       GEOMETRY(Point, 4326) NOT NULL
);

CREATE INDEX idx_calles_vertices_geom
ON vialis.calles_vertices
USING GIST (geom);

-- Aristas dirigidas de la red vial. Un costo inverso de -1 indica que la calle
-- no es transitable desde destino hacia origen, según la convención pgRouting.
CREATE TABLE vialis.calles (
    id_calle                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    osm_way_id                 BIGINT NOT NULL,
    nombre                     TEXT,
    tipo                       TEXT NOT NULL,
    origen                     BIGINT NOT NULL
        REFERENCES vialis.calles_vertices(id_vertice),
    destino                    BIGINT NOT NULL
        REFERENCES vialis.calles_vertices(id_vertice),
    costo                      DOUBLE PRECISION NOT NULL CHECK (costo > 0),
    costo_inverso              DOUBLE PRECISION NOT NULL
        CHECK (costo_inverso > 0 OR costo_inverso = -1),
    sentido_osm                TEXT,
    acceso_osm                 TEXT,
    acceso_vehiculo_motor_osm  TEXT,
    junction_osm               TEXT,
    bridge_osm                 TEXT,
    tunnel_osm                 TEXT,
    layer_osm                  SMALLINT NOT NULL DEFAULT 0,
    geom                       GEOMETRY(LineString, 4326) NOT NULL,
    CONSTRAINT calles_vertices_distintos CHECK (origen <> destino)
);

CREATE INDEX idx_calles_geom
ON vialis.calles
USING GIST (geom);

CREATE INDEX idx_calles_origen
ON vialis.calles (origen);

CREATE INDEX idx_calles_destino
ON vialis.calles (destino);

CREATE INDEX idx_calles_osm_way_id
ON vialis.calles (osm_way_id);
-- Conexiones entre recorridos --
--
-- Un par ordenado (origen, destino) significa que se puede viajar en el
-- recorrido de origen, bajarse en `id_parada_bajada`, caminar hasta
-- `id_parada_subida` y tomar el recorrido de destino. El par es ordenado porque
-- la factibilidad de un itinerario depende del sentido: el trasbordo tiene que
-- caer despues de donde la persona subio al primer recorrido y antes de donde
-- baja del segundo, y esa pregunta no es simetrica.
--
-- La tabla guarda un unico punto de trasbordo por par: el de menor caminata.
-- Guardar todos multiplicaria las filas por la cantidad de esquinas que dos
-- recorridos comparten, que en el AMBA son decenas. La consecuencia esta
-- documentada en sql/recorridos/README.md: un par puede descartarse por orden
-- aunque otro punto de trasbordo si lo respetara.
CREATE TABLE vialis.conexiones_recorridos (
    id_recorrido_origen        BIGINT NOT NULL
        REFERENCES vialis.recorridos(id_recorrido) ON DELETE CASCADE,
    id_recorrido_destino       BIGINT NOT NULL
        REFERENCES vialis.recorridos(id_recorrido) ON DELETE CASCADE,
    id_parada_bajada           BIGINT NOT NULL
        REFERENCES vialis.paradas(id_parada),
    id_parada_subida           BIGINT NOT NULL
        REFERENCES vialis.paradas(id_parada),
    distancia_caminata_metros  INTEGER NOT NULL
        CHECK (distancia_caminata_metros >= 0),
    CONSTRAINT conexiones_recorridos_distintos
        CHECK (id_recorrido_origen <> id_recorrido_destino),
    PRIMARY KEY (id_recorrido_origen, id_recorrido_destino)
);

-- La busqueda de itinerarios llega por los dos lados: los recorridos que
-- sirven el origen y los que sirven el destino. El indice por destino
-- acompaña a la clave primaria, que ya cubre el origen.
CREATE INDEX idx_conexiones_recorridos_destino
ON vialis.conexiones_recorridos (id_recorrido_destino);

-- Combinaciones origen-destino por banda horaria --
--
-- Un viaje con mas de una etapa es un viaje que necesito trasbordo. La fuente
-- no dice donde ocurrio ni que lineas se usaron, asi que esta tabla agrega
-- unicamente lo que si esta: cuanta gente va de una celda a otra, en que hora,
-- habiendo tenido que combinar.
--
-- `viajes_estimados` pertenece al par de celdas y no a ningun itinerario
-- concreto. No se puede saber cual de las combinaciones factibles uso la gente,
-- de modo que repartir este numero entre ellas seria inventar datos.
CREATE TABLE vialis.combinaciones_od (
    h3_origen         H3INDEX NOT NULL
        REFERENCES vialis.hexagonos_viajes(indice_h3),
    h3_destino        H3INDEX NOT NULL
        REFERENCES vialis.hexagonos_viajes(indice_h3),
    rango_horario     SMALLINT NOT NULL,
    viajes_estimados  DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (h3_origen, h3_destino, rango_horario)
);

-- La consulta siempre filtra por una hora y pide los flujos mas grandes de esa
-- hora, asi que el indice ordena por volumen dentro de cada banda horaria.
CREATE INDEX idx_combinaciones_od_banda_horaria
ON vialis.combinaciones_od (rango_horario, viajes_estimados DESC);

-- Ranking de combinaciones de lineas --
--
-- Cada fila es un par ordenado de recorridos con los viajes que se le atribuyen.
-- Es la tabla que lee GET /transfers, y esta precalculada por dos motivos: la
-- agregacion recorre todos los flujos de la ciudad, y el endpoint pagina, de
-- modo que necesita un total exacto y barato.
--
-- COMO SE ATRIBUYE
--
-- La fuente no dice que lineas uso la gente. Lo que se hace es repartir cada
-- flujo O-D en partes iguales entre sus combinaciones factibles: un flujo de
-- 4.000 viajes con 4 combinaciones aporta 1.000 a cada una. Es un supuesto, no
-- una medicion, y por eso `alternativas_promedio` viaja al lado del numero: un
-- par cuyo volumen salio de repartos entre 2 alternativas es una afirmacion
-- fuerte, y uno que salio de repartos entre 30 es una conjetura. La interfaz
-- tiene que poder distinguirlos.
--
-- BANDA HORARIA
--
-- `rango_horario` NULL es la fila del dia entero, y las 24 filas con hora son el
-- desglose. Se precalculan las dos cosas porque agrupar el desglose en cada
-- request para responder "todo el dia" es justamente el trabajo que esta tabla
-- existe para evitar. El indice unico usa NULLS NOT DISTINCT para que la fila
-- del dia entero tenga la misma garantia de unicidad que las otras.
CREATE TABLE vialis.combinaciones_lineas (
    id_recorrido_primero   BIGINT NOT NULL
        REFERENCES vialis.recorridos(id_recorrido) ON DELETE CASCADE,
    id_recorrido_segundo   BIGINT NOT NULL
        REFERENCES vialis.recorridos(id_recorrido) ON DELETE CASCADE,
    rango_horario          SMALLINT
        CHECK (rango_horario IS NULL OR rango_horario BETWEEN 0 AND 23),
    viajes_estimados       DOUBLE PRECISION NOT NULL,
    -- Promedio ponderado por volumen de cuantas combinaciones factibles tenian
    -- los flujos de los que salio `viajes_estimados`.
    alternativas_promedio  REAL NOT NULL CHECK (alternativas_promedio >= 1),
    -- Hora en la que este par concentra mas viajes. En las filas con hora
    -- repite `rango_horario`; en la del dia entero es el dato que la interfaz
    -- muestra como "pico".
    rango_horario_pico     SMALLINT NOT NULL
        CHECK (rango_horario_pico BETWEEN 0 AND 23),

    -- Las dos zonas que la combinacion une, y cuantos pares origen-destino
    -- distintos sirve.
    --
    -- Es la celda que mas viajes concentra de cada lado, no el promedio de las
    -- coordenadas: un promedio puede caer donde no viaja nadie, mientras que la
    -- celda dominante es un lugar real con datos reales. Representa a su zona,
    -- no es el punto exacto, y la interfaz lo dice asi.
    --
    -- Reemplaza a la tabla de "los tres viajes mas grandes", que era una
    -- muestra enganosa: sobre el dataset completo el mayor par origen-destino
    -- de una combinacion explica entre el 5 y el 23 % de su volumen, y los tres
    -- juntos entre el 14 y el 56 %. Mostrarlos como el detalle de la fila
    -- presentaba una quinta parte del total como si fuera el todo.
    h3_origen_dominante    H3INDEX NOT NULL
        REFERENCES vialis.hexagonos_viajes(indice_h3),
    h3_destino_dominante   H3INDEX NOT NULL
        REFERENCES vialis.hexagonos_viajes(indice_h3),
    nombre_origen          TEXT NOT NULL,
    nombre_destino         TEXT NOT NULL,
    pares_od_distintos     INTEGER NOT NULL CHECK (pares_od_distintos >= 1)
);

CREATE UNIQUE INDEX idx_combinaciones_lineas_par
ON vialis.combinaciones_lineas (
    id_recorrido_primero,
    id_recorrido_segundo,
    rango_horario
) NULLS NOT DISTINCT;

-- El ranking siempre filtra por una banda horaria (o por la fila del dia
-- entero) y pide las mas grandes primero.
CREATE INDEX idx_combinaciones_lineas_ranking
ON vialis.combinaciones_lineas (rango_horario, viajes_estimados DESC);

