CREATE TABLE vialis.viajes
(
    id_tarjeta                 BIGINT,
    id_viaje                   SMALLINT,
    cantidad_etapas            SMALLINT,
    rango_horario              SMALLINT,

    etapas_subte               SMALLINT,
    etapas_tren                SMALLINT,
    etapas_colectivo           SMALLINT,

    geom_origen                GEOMETRY(Point, 4326),

    geom_destino               GEOMETRY(Point, 4326),

    h3_origen                  H3INDEX,
    h3_destino                 H3INDEX,

    departamento_origen_viaje  CHAR(5),
    departamento_destino_viaje CHAR(5),

    factor_expansion_viaje     REAL,

    etapas_incompletas         CHAR(1),
    genero                     CHAR(1),
    grupo_edad                 SMALLINT
);

-- Hexagono H3 --
CREATE TABLE vialis.hexagonos_viajes (
    indice_h3 H3INDEX PRIMARY KEY,
    punto_maxima_concurrencia GEOMETRY(Point, 4326),
    concurrencia DOUBLE PRECISION NOT NULL
);

-- Matriz origen-destino --
CREATE TABLE vialis.matriz_origen_destino (
    h3_origen H3INDEX NOT NULL
        REFERENCES vialis.hexagonos_viajes(indice_h3),
    h3_destino H3INDEX NOT NULL
        REFERENCES vialis.hexagonos_viajes(indice_h3),
    cantidad_viajes DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (h3_origen, h3_destino)
);

-- Cuadros tarifarios de colectivos por jurisdicción y distancia. Los importes
-- se guardan en centavos de ARS; distancia_max_metros NULL representa +infinito.
CREATE TABLE vialis.tarifas_colectivo (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jurisdiccion                    TEXT NOT NULL
        CHECK (jurisdiccion IN ('caba', 'province', 'national')),
    distancia_min_metros            INTEGER NOT NULL CHECK (distancia_min_metros >= 0),
    distancia_max_metros            INTEGER,
    tarifa_registrada_centavos      INTEGER NOT NULL CHECK (tarifa_registrada_centavos >= 0),
    tarifa_sin_registrar_centavos   INTEGER NOT NULL CHECK (tarifa_sin_registrar_centavos >= 0),
    CONSTRAINT tarifas_colectivo_distancia_valida CHECK (
        distancia_max_metros IS NULL
        OR distancia_max_metros > distancia_min_metros
    ),
    UNIQUE (jurisdiccion, distancia_min_metros)
);

-- Recorridos de colectivos GTFS --
CREATE TABLE vialis.recorridos (
    id_recorrido                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gtfs_route_id               TEXT NOT NULL,
    gtfs_shape_id               TEXT NOT NULL,
    nombre_publico              TEXT NOT NULL,
    linea                       TEXT NOT NULL,
    ramal                       TEXT NOT NULL,
    direction_id                SMALLINT NOT NULL CHECK (direction_id IN (0, 1)),
    destino                     TEXT,
    descripcion                 TEXT,
    geom                        GEOMETRY(LineString, 4326) NOT NULL,
    distancia_metros            INTEGER NOT NULL CHECK (distancia_metros >= 0),
    tiempo_total_minutos        SMALLINT CHECK (tiempo_total_minutos >= 0),
    caudal_pasajeros            INTEGER CHECK (caudal_pasajeros >= 0),
    ingreso_economico           BIGINT CHECK (ingreso_economico >= 0),
    UNIQUE (gtfs_route_id, direction_id)
);

CREATE INDEX idx_recorridos_geom
ON vialis.recorridos
USING GIST (geom);

-- El índice anterior es sobre la columna geom pelada, así que un ST_DWithin en
-- geography no puede usarlo y degrada a recorrer la tabla entera. La búsqueda
-- de corredores detrás de POST /lines/similar filtra en metros y no en grados,
-- por lo que necesita el índice sobre la expresión casteada. Es la misma
-- respuesta que ya da idx_recorridos_paradas_tramo_geography por la misma
-- razón. Se conservan los dos: el geométrico sigue sirviendo al filtro por caja
-- del listado, que compara cajas en grados.
CREATE INDEX idx_recorridos_geom_geography
ON vialis.recorridos
USING GIST ((geom::geography));

-- Una parada es una ubicación física y puede pertenecer a varios recorridos.
CREATE TABLE vialis.paradas (
    id_parada                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gtfs_stop_id                TEXT NOT NULL UNIQUE,
    codigo                      TEXT,
    nombre                      TEXT NOT NULL,
    posicion                    GEOMETRY(Point, 4326) NOT NULL
);

CREATE INDEX idx_paradas_posicion
ON vialis.paradas
USING GIST (posicion);

-- Relación ordenada entre un recorrido y sus paradas. El tramo y la distancia
-- son NULL para la última parada, porque no existe una parada siguiente.
CREATE TABLE vialis.recorridos_paradas (
    id_recorrido                       BIGINT NOT NULL
        REFERENCES vialis.recorridos(id_recorrido) ON DELETE CASCADE,
    id_parada                          BIGINT NOT NULL
        REFERENCES vialis.paradas(id_parada),
    nro_parada                         INTEGER NOT NULL CHECK (nro_parada >= 0),
    tramo_hasta_siguiente              GEOMETRY(LineString, 4326),
    distancia_hasta_siguiente_metros   INTEGER
        CHECK (distancia_hasta_siguiente_metros >= 0),
    tiempo_valle_hasta_siguiente_segundos INTEGER
        CONSTRAINT recorridos_paradas_tiempo_valle_positivo
        CHECK (tiempo_valle_hasta_siguiente_segundos > 0),
    tiempo_tipico_hasta_siguiente_segundos INTEGER
        CONSTRAINT recorridos_paradas_tiempo_tipico_positivo
        CHECK (tiempo_tipico_hasta_siguiente_segundos > 0),
    tiempo_pico_hasta_siguiente_segundos INTEGER
        CONSTRAINT recorridos_paradas_tiempo_pico_positivo
        CHECK (tiempo_pico_hasta_siguiente_segundos > 0),
    cantidad_muestras_tiempo           INTEGER NOT NULL DEFAULT 0
        CHECK (cantidad_muestras_tiempo >= 0),
    CONSTRAINT recorridos_paradas_muestras_tiempo_validas CHECK (
        (
            tiempo_valle_hasta_siguiente_segundos IS NULL
            AND tiempo_tipico_hasta_siguiente_segundos IS NULL
            AND tiempo_pico_hasta_siguiente_segundos IS NULL
            AND cantidad_muestras_tiempo = 0
        )
        OR (
            tiempo_valle_hasta_siguiente_segundos IS NOT NULL
            AND tiempo_tipico_hasta_siguiente_segundos IS NOT NULL
            AND tiempo_pico_hasta_siguiente_segundos IS NOT NULL
            AND tiempo_valle_hasta_siguiente_segundos
                <= tiempo_tipico_hasta_siguiente_segundos
            AND tiempo_tipico_hasta_siguiente_segundos
                <= tiempo_pico_hasta_siguiente_segundos
            AND cantidad_muestras_tiempo > 0
        )
    ),
    PRIMARY KEY (id_recorrido, nro_parada)
);

CREATE INDEX idx_recorridos_paradas_id_parada
ON vialis.recorridos_paradas (id_parada);

CREATE INDEX idx_recorridos_paradas_tramo_geography
ON vialis.recorridos_paradas
USING GIST ((tramo_hasta_siguiente::geography))
WHERE tramo_hasta_siguiente IS NOT NULL;
